import { StyleSheet, Platform } from "react-native";
import { COLORS } from "@/src/constants/theme";

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.navy },
  scroll: { padding: 16, paddingTop: Platform.OS === "ios" ? 56 : 36 },
  center: { flex: 1, backgroundColor: COLORS.navy, justifyContent: "center", alignItems: "center" },
  emptyText: { color: COLORS.gray400, fontSize: 16 },
  backBtn: { marginTop: 16, paddingHorizontal: 20, paddingVertical: 10, backgroundColor: COLORS.crimson, borderRadius: 10 },
  backText: { color: COLORS.white, fontWeight: "700" },
  backRow: { flexDirection: "row", alignItems: "center", gap: 8, marginBottom: 14 },
  backLabel: { color: COLORS.white, fontSize: 15, fontWeight: "600" },
  card: {
    backgroundColor: "rgba(255,255,255,0.05)", borderRadius: 14, padding: 14,
    marginBottom: 8, borderWidth: 1, borderColor: "rgba(255,255,255,0.06)",
  },
  paidCard: { borderColor: "rgba(34,197,94,0.3)", backgroundColor: "rgba(34,197,94,0.08)" },
  cashCard: { borderColor: "rgba(245,166,35,0.3)", backgroundColor: "rgba(245,166,35,0.08)" },
  invoiceCard: { borderColor: "rgba(168,85,247,0.3)", backgroundColor: "rgba(168,85,247,0.08)" },
  cardTitle: { color: COLORS.white, fontSize: 15, fontWeight: "800", marginBottom: 12 },
  paymentRow: { flexDirection: "row", alignItems: "center", gap: 10, marginBottom: 8 },
  paymentMethod: { color: COLORS.white, fontSize: 15, fontWeight: "600" },
  paymentNote: { color: COLORS.gray400, fontSize: 12 },
  paidBadge: { flexDirection: "row", alignItems: "center", gap: 6, backgroundColor: "rgba(34,197,94,0.15)", paddingHorizontal: 12, paddingVertical: 6, borderRadius: 8 },
  paidText: { color: COLORS.green, fontSize: 13, fontWeight: "700" },
  cashBadge: { flexDirection: "row", alignItems: "center", gap: 6, backgroundColor: "rgba(245,166,35,0.15)", paddingHorizontal: 12, paddingVertical: 6, borderRadius: 8 },
  cashText: { color: COLORS.gold, fontSize: 13, fontWeight: "700" },
  cashInputRow: { flexDirection: "row", alignItems: "center", backgroundColor: "rgba(255,255,255,0.08)", borderRadius: 12, paddingHorizontal: 14 },
  currencySign: { color: COLORS.gold, fontSize: 22, fontWeight: "800", marginRight: 6 },
  cashInput: { flex: 1, color: COLORS.white, fontSize: 22, fontWeight: "700", paddingVertical: 14 },
  cashHint: { color: COLORS.gray500, fontSize: 11, marginTop: 6 },
  infoRow: { flexDirection: "row", alignItems: "center", gap: 10, marginBottom: 8 },
  infoText: { color: COLORS.gray400, fontSize: 14 },
  tripRow: { flexDirection: "row", alignItems: "flex-start", gap: 10 },
  tripDot: { width: 12, height: 12, borderRadius: 6, marginTop: 3, borderWidth: 2.5 },
  tripInfo: { flex: 1 },
  tripLabel: { color: COLORS.gray500, fontSize: 10, fontWeight: "600", textTransform: "uppercase", letterSpacing: 0.5, marginBottom: 1 },
  tripAddress: { color: COLORS.white, fontSize: 13, fontWeight: "600", lineHeight: 18 },
  tripLine: { width: 1.5, height: 16, backgroundColor: "rgba(255,255,255,0.08)", marginLeft: 5, marginVertical: 1 },
  rideGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  rideItem: {
    width: "47%", backgroundColor: "rgba(255,255,255,0.04)", borderRadius: 10,
    paddingVertical: 8, paddingHorizontal: 6, alignItems: "center",
  },
  rideValue: { color: COLORS.white, fontSize: 13, fontWeight: "700", marginTop: 3 },
  rideLabel: { color: COLORS.gray500, fontSize: 10, marginTop: 1 },
  actionsWrap: { gap: 10, marginTop: 10 },
  actionBtn: {
    flexDirection: "row", alignItems: "center", justifyContent: "center",
    gap: 10, paddingVertical: 15, borderRadius: 14,
  },
  actionText: { color: COLORS.white, fontSize: 16, fontWeight: "800" },
  navBtn: {
    flexDirection: "row", alignItems: "center", justifyContent: "center",
    gap: 6, backgroundColor: "#3B82F6", borderRadius: 12, paddingVertical: 10, marginTop: 10,
  },
  navBtnText: { color: COLORS.white, fontWeight: "700", fontSize: 14 },
  invoiceBadge: { flexDirection: "row", alignItems: "center", gap: 6, backgroundColor: "rgba(168,85,247,0.15)", paddingHorizontal: 10, paddingVertical: 6, borderRadius: 10 },
  invoiceText: { fontSize: 13, fontWeight: "700", color: "#A855F7" },
});
